# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='phone'),
        ),
    ]
