# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181003_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermail',
            name='email',
            field=models.CharField(max_length=255, verbose_name='email'),
        ),
    ]
