# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 07:18
from __future__ import unicode_literals

import core.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_style_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.helper.RandomFileName('poster/'))),
            ],
        ),
        migrations.AlterField(
            model_name='style',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'landscape'), ('portrait', 'portrait')], default='portrait', max_length=10, verbose_name='orientation'),
        ),
    ]
